version: '3.7'
services:
  web:
    image: httpd
    container_name: web
    ports:
      - "80:80"
    networks: 
      elk:
    depends_on: 
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk
  fluentd:
    image: fluentd-elasticsearch
    container_name: fluentd
    volumes:
      - type: bind
        source: ./config/fluent.conf
        target: /fluentd/etc/fluent.conf
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
      - "8888:8888"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    volumes:
      - type: bind
        source: ./config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
